import { type LucideIcon } from "lucide-react";
import {
  Route,
  FileText,
  ShieldCheck,
  BadgeCheck,
  Repeat,
  UserCog,
  Box,
  Users,
  ArrowUpCircle,
  ScrollText,
  Coins,
  Shuffle,
  Fuel,
  Signature,
  PlugZap,
  SquareKanban,
  Network,
  Droplet,
  Wallet,
  Link,
  RefreshCw,
  Gift,
  BookOpen,
  Code,
  Boxes,
  HandCoins,
  MessageSquare,
  Headphones,
  CircleHelp,
  Rocket,
  Vote,
  Twitter,
  Send,
  LineChart,
  Circle,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "route": Route,
  "file-text": FileText,
  "shield-check": ShieldCheck,
  "badge-check": BadgeCheck,
  "repeat": Repeat,
  "user-cog": UserCog,
  "box": Box,
  "users": Users,
  "arrow-up-circle": ArrowUpCircle,
  "scroll-text": ScrollText,
  "coins": Coins,
  "shuffle": Shuffle,
  "fuel": Fuel,
  "signature": Signature,
  "plug": PlugZap,
  "square-kanban": SquareKanban,
  "network": Network,
  "droplet": Droplet,
  "wallet": Wallet,
  "link": Link,
  "refresh-cw": RefreshCw,
  "gift": Gift,
  "book-open": BookOpen,
  "code": Code,
  "boxes": Boxes,
  "hand-coins": HandCoins,
  "message-square": MessageSquare,
  "headphones": Headphones,
  "circle-help": CircleHelp,
  "rocket": Rocket,
  "vote": Vote,
  "twitter": Twitter,
  "discord": Send,
  "line-chart": LineChart,
  "coinmarketcap": LineChart,
  "linktree": Link,
  "default": Circle,
};